<?php
/************************************************************************/

/* This program is free software; you can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/*                                                                      */
/* This program is distributed in the hope that it will be useful, but  */
/* WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU     */
/* General Public License for more details.                             */
/*                                                                      */
/* You should have received a copy of the GNU General Public License    */
/* along with this program; if not, write to the Free Software          */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  */
/* USA                                                                  */
/************************************************************************/

$modversion['name'] = 'HLStats';
$modversion['version'] = '1.30';
$modversion['description'] = 'HLStats for Xoops';
$modversion['author'] = "<a href='mailto:admin@csmapcentral.com'>Jon Langevin aka bd_csmc aka intel352</a>";
$modversion['credits'] = 'Based on HLStats v1.30 Beta.<br>Ported to Xoops2 with enhancements/fixes by <a href=http://www.csmapcentral.com>CSMapCentral.com</a><br>Xoops2 port maintained by bd_csmc.';
$modversion['help'] = '';
$modversion['license'] = 'GNU General Public License (GPL)';
$modversion['official'] = 0;
$modversion['image'] = 'images/hlstats_slogo.png';
$modversion['dirname'] = 'xhlstats';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/hlstats.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'hlstats_Actions';
$modversion['tables'][1] = 'hlstats_Awards';
$modversion['tables'][2] = 'hlstats_Clans';
$modversion['tables'][3] = 'hlstats_ClanTags';
$modversion['tables'][4] = 'hlstats_Games';
$modversion['tables'][5] = 'hlstats_HostGroups';
$modversion['tables'][6] = 'hlstats_Options';
$modversion['tables'][7] = 'hlstats_Players';
$modversion['tables'][8] = 'hlstats_PlayerNames';
$modversion['tables'][9] = 'hlstats_PlayerUniqueIds';
$modversion['tables'][10] = 'hlstats_Roles';
$modversion['tables'][11] = 'hlstats_Servers';
$modversion['tables'][12] = 'hlstats_Teams';
$modversion['tables'][13] = 'hlstats_Weapons';
$modversion['tables'][14] = 'hlstats_Events_Admin';
$modversion['tables'][15] = 'hlstats_Events_ChangeName';
$modversion['tables'][16] = 'hlstats_Events_ChangeRole';
$modversion['tables'][17] = 'hlstats_Events_ChangeTeam';
$modversion['tables'][18] = 'hlstats_Events_Connects';
$modversion['tables'][19] = 'hlstats_Events_Disconnects';
$modversion['tables'][20] = 'hlstats_Events_Entries';
$modversion['tables'][21] = 'hlstats_Events_Frags';
$modversion['tables'][22] = 'hlstats_Events_PlayerActions';
$modversion['tables'][23] = 'hlstats_Events_PlayerPlayerActions';
$modversion['tables'][24] = 'hlstats_Events_Rcon';
$modversion['tables'][25] = 'hlstats_Events_Suicides';
$modversion['tables'][26] = 'hlstats_Events_TeamBonuses';
$modversion['tables'][27] = 'hlstats_Events_Teamkills';
$modversion['tables'][28] = 'hlstats_Events_Statsme';
$modversion['tables'][29] = 'hlstats_Events_Statsme2';
$modversion['tables'][30] = 'hlstats_Events_StatsmeTime';
$modversion['tables'][31] = 'hlstats_Events_StatsmeLatency';
$modversion['tables'][32] = 'hlstats_server_addons';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
/*$modversion['blocks'][1]['file'] = "Donat_o_Meter.php";
$modversion['blocks'][1]['name'] = "Donat_o_Meter";
$modversion['blocks'][1]['description'] = "Donations Block";
$modversion['blocks'][1]['show_func'] = "b_donations_donatometer_show";
$modversion['blocks'][1]['template'] = 'donations_donatometer.html';*/

// Menu
$modversion['hasMain'] = 1;

global $xoopsDB;

$result = $xoopsDB->query('SELECT code, name FROM ' . $xoopsDB->prefix('hlstats_Games') . " WHERE hidden = '0' ORDER BY name ASC");
$i = 1;

while (list($game, $gametitle) = $xoopsDB->fetchRow($result)) {
    $modversion['sub'][$i]['name'] = $gametitle;

    $modversion['sub'][$i]['url'] = 'index.php?game=' . $game;

    $sresult = $xoopsDB->query('SELECT serverId, name FROM ' . $xoopsDB->prefix('hlstats_Servers') . " WHERE game = '$game' ORDER BY name ASC");

    while (list($serverId, $name) = $xoopsDB->fetchRow($sresult)) {
        $i++;

        $modversion['sub'][$i]['name'] = '-- ' . $name;

        $modversion['sub'][$i]['url'] = 'index.php?mode=live_stats&server=' . $serverId;
    }

    $i++;
}
$modversion['sub'][$i]['name'] = 'Search Player Database';
$modversion['sub'][$i]['url'] = 'index.php?mode=search';
$i++;
$modversion['sub'][$i]['name'] = 'Help';
$modversion['sub'][$i]['url'] = 'index.php?mode=help';

// Templates
/*$modversion['templates'][1]['file'] = 'donations_main.html';
$modversion['templates'][1]['description'] = 'Donations Main Template';*/
